@startuml ERD Design

class StageRecord {
    +id
    effective_date
    insert_date
    external_refrence
    company_name
    amount
    term
    process_status
    process_action
    -batch_id
}

class StageBatch {
    +id
    client_account
    start_date
    end_date
    file_hash
    file_name
    success_count
    failure_count
    batch_status
}

class MasterRecord {
    +id
    external_reference
    company_name
    amount
    status
    from_date
    to_date
    has_changes
    last_updated
    is_deleted
    is_placeholder
    -batch_id
    -client_account_id
}

class ClientAccount {
    +id
    account_number
    last_updated
}

StageRecord }-- StageBatch
MasterRecord }-- ClientAccount
MasterRecord }-- StageBatch

@enduml
