@startuml ERD Design

class StageRecord {
    +id
    effective_date
    insert_date
    external_refrence
    company_name
    amount
    status
    -batch_id
}

class Batch {
    +id
    client_account
    start_date
    end_date
    success_count
    failure_count
    batch_status
}

class MasterRecord {
    +id
    external_reference
    company_name
    amount
    status
    from_date
    to_date
    is_deleted
    last_updated
    has_changes
    batch_reference
    -client_account_id
}

class ClientAccount {
    +id
    account_number
    last_updated
}

StageRecord }-- Batch
MasterRecord }-- ClientAccount

@enduml
